version: '3'

services:
  pgsql:
    container_name: rsschool-pgsql
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - POSTGRES_PORT=${DB_PORT}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - rsschool-network

  nodejs:
    container_name: rsschool-nodejs
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
      args:
        - PORT=${PORT}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - pgsql
    volumes:
      - node_logs:/var/log/rsschool
    networks:
      - rsschool-network

volumes:
  pg_data:
    external: true
  node_logs:
    external: true

networks:
  rsschool-network:
    driver: bridge
    name: rsschool-network
